# Generated by Django 4.1.5 on 2023-02-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='Name',
        ),
    ]
